# Generated by Django 5.2 on 2025-04-24 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('cod_cat', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('cod_list', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('cod_prod', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('cod_cat', models.ForeignKey(db_column='cod_cat', on_delete=django.db.models.deletion.CASCADE, to='app.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Lista_Produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_list', models.ForeignKey(db_column='cod_list', on_delete=django.db.models.deletion.CASCADE, to='app.lista')),
                ('cod_prod', models.ForeignKey(db_column='cod_prod', on_delete=django.db.models.deletion.CASCADE, to='app.produtos')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('cod_prod', 'cod_list'), name='CompositePrimaryKey')],
            },
        ),
    ]
