# Generated by Django 5.2.1 on 2025-06-02 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria_Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.ForeignKey(db_column='cod_cat', on_delete=django.db.models.deletion.CASCADE, to='app.categoria')),
                ('produto', models.ForeignKey(db_column='cod_prod', on_delete=django.db.models.deletion.CASCADE, to='app.produto')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('categoria', 'produto'), name='Categoria_Produto_CompositePrimaryKey')],
            },
        ),
    ]
