# Generated by Django 5.2.1 on 2025-06-02 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='image_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
