# Generated by Django 5.2.1 on 2025-06-02 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_produto_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='description',
            field=models.TextField(default='descrição aqui'),
            preserve_default=False,
        ),
    ]
