# Generated by Django 5.2 on 2025-04-24 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_lista_produtos_compositeprimarykey_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lista_produtos',
            name='nome',
        ),
    ]
