# Generated by Django 5.2 on 2025-04-24 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_lista_produtos_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produtos',
            name='cod_cat',
        ),
        migrations.CreateModel(
            name='Categoria_Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cod_cat', models.ForeignKey(db_column='cod_cat', on_delete=django.db.models.deletion.CASCADE, to='app.categoria')),
                ('cod_prod', models.ForeignKey(db_column='cod_prod', on_delete=django.db.models.deletion.CASCADE, to='app.produtos')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('cod_cat', 'cod_prod'), name='Categoria_Produto_CompositePrimaryKey')],
            },
        ),
    ]
