# Generated by Django 5.2 on 2025-05-07 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_lista_hash_value_remove_produtos_hash_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria_produto',
            name='nome',
        ),
    ]
