# Generated by Django 5.2.1 on 2025-05-09 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_categoria_produto_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria_produto',
            name='nome',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='lista_produtos',
            name='nome',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
