# Generated by Django 5.2 on 2025-04-24 21:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='lista_produtos',
            name='CompositePrimaryKey',
        ),
        migrations.AddField(
            model_name='lista_produtos',
            name='nome',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='lista_produtos',
            constraint=models.UniqueConstraint(fields=('cod_prod', 'cod_list'), name='Lista_Produtos_CompositePrimaryKey'),
        ),
    ]
