# Generated by Django 5.2 on 2025-05-07 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_produtos_cod_cat_categoria_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='hash_value',
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
    ]
